[redshift]
; Set the day and night screen temperatures
temp-day=4500
temp-night=4500

; Enable smooth transitions
transition=0

; Set the location provider
location-provider=manual

[manual]
; Example: Dhulikhel, Nepal
lat=27.62
lon=85.54
